name: remitx_native
description: "Platform specific APIs used by Remit."
version: 0.0.1
homepage:

environment:
    sdk: ">=3.3.0 <4.0.0"
    flutter: ">=3.3.0"

dependencies:
    flutter:
        sdk: flutter
    plugin_platform_interface: ^2.0.2

dev_dependencies:
    flutter_test:
        sdk: flutter
    zlint:
        git:
            url: https://github.com/zyrouge/dart_zlint.git

flutter:
    plugin:
        platforms:
            android:
                package: me.zyrouge.remitx_native
                pluginClass: RemitxNativePlugin
