name: remitx
description: A new Flutter project.
publish_to: none

version: 1.0.0+1

environment:
    sdk: ">=3.3.0 <4.0.0"

dependencies:
    flutter:
        sdk: flutter
    flutter_svg: ^2.0.9
    freezed_annotation: ^2.4.1
    ionicons: ^0.2.2
    json_annotation: ^4.8.1
    path: ^1.9.0
    path_provider: ^2.1.2
    provider: ^6.1.1
    remit:
        git:
            url: https://github.com/zyrouge/dart_remit.git
    sprintf: ^7.0.0

dev_dependencies:
    build_runner: ^2.4.8
    freezed: ^2.4.7
    json_serializable: ^6.7.1
    zlint:
        git:
            url: https://github.com/zyrouge/dart_zlint.git

flutter:
    uses-material-design: false

    assets:
        - assets/i18n/
        - assets/images/logo-transparent.svg

    fonts:
        - family: Inter
          fonts:
              - asset: assets/fonts/Inter-Regular.ttf
              - asset: assets/fonts/Inter-Bold.ttf
                weight: 700
