[input]:
files = ["../i18n/**.toml"]
format = toml
fallback = ["../i18n/en.toml"]

[schema]:
file = "./schema.json"
format = toml

[output]:
dir = "../dist-i18n"
format = json
stringFormat = format-string

[hooks]
files = []
