[input]
files = ["../i18n/**.toml"]
format = "toml"
fallback = ["../i18n/en.toml"]

[schema]
file = "./schema.toml"
format = "toml"

[output]
dir = "../assets/i18n"
format = "json"
stringFormat = "format-string"

[hooks]
files = ["./hooks/dart-sync.js"]
