[[keys]]
name = "Send"
description = "Send"

[[keys]]
name = "Receive"
description = "Receive"

[[keys]]
name = "Settings"
description = "Settings"

[[keys]]
name = "ChooseABelowOptionWhenYouAreReady"
description = "Choose a below option when you are ready."

[[keys]]
name = "Back"
description = "Back"

[[keys]]
name = "Username"
description = "Username"

[[keys]]
name = "Theme"
description = "Theme"

[[keys]]
name = "System"
description = "System"

[[keys]]
name = "Light"
description = "Light"

[[keys]]
name = "Dark"
description = "Dark"

[[keys]]
name = "UsernameTooShort"
description = "Username too short"

[[keys]]
name = "Language"
description = "Language"

[[keys]]
name = "Ask"
description = "Ask"

[[keys]]
name = "AllowAll"
description = "Allow all"

[[keys]]
name = "ConnectionAcceptMode"
description = "Connection accept mode"
