[[keys]]
name = "Send"
description = "Send"

[[keys]]
name = "Receive"
description = "Receive"

[[keys]]
name = "Settings"
description = "Settings"

[[keys]]
name = "ChooseABelowOptionWhenYouAreReady"
description = "Choose a below option when you are ready."

[[keys]]
name = "Back"
description = "Back"

[[keys]]
name = "Username"
description = "Username"

[[keys]]
name = "Theme"
description = "Theme"

[[keys]]
name = "System"
description = "System"

[[keys]]
name = "Light"
description = "Light"

[[keys]]
name = "Dark"
description = "Dark"

[[keys]]
name = "UsernameTooShort"
description = "Username too short"

[[keys]]
name = "Language"
description = "Language"

[[keys]]
name = "Ask"
description = "Ask"

[[keys]]
name = "AllowAll"
description = "Allow all"

[[keys]]
name = "ConnectionAcceptMode"
description = "Connection accept mode"

[[keys]]
name = "Sender"
description = "Sender"

[[keys]]
name = "SenderConfigurationMessage"
description = "Before you start sending, ensure the configuration."

[[keys]]
name = "Start"
description = "Start"

[[keys]]
name = "NetworkHost"
description = "Network host"

[[keys]]
name = "NetworkPort"
description = "Network port"

[[keys]]
name = "InvalidPortValue"
description = "Invalid port value"

[[keys]]
name = "Secure"
description = "Secure"

[[keys]]
name = "Yes"
description = "Yes"

[[keys]]
name = "No"
description = "No"

[[keys]]
name = "ServerExitMessage"
description = "This will terminate the server and all of the ongoing transfers immediately."

[[keys]]
name = "Accept"
description = "Accept"

[[keys]]
name = "Deny"
description = "Deny"

[[keys]]
name = "ExitQuestion"
description = "Exit?"

[[keys]]
name = "Exit"
description = "Exit"

[[keys]]
name = "Cancel"
description = "Cancel"

[[keys]]
name = "AddFile"
description = "Add file"

[[keys]]
name = "AddFolder"
description = "Add folder"

[[keys]]
name = "RemoveSelected"
description = "Remove selected"

[[keys]]
name = "ThisIsEmptyMaybeAddSomeFiles"
description = "This is empty. Maybe add some files?"

[[keys]]
name = "Loading"
description = "Loading..."

[[keys]]
name = "Starting"
description = "Starting..."

[[keys]]
name = "XKb"
description = "X KB"
parameters = ["x"]

[[keys]]
name = "XMb"
description = "X MB"
parameters = ["x"]

[[keys]]
name = "XGb"
description = "X GB"
parameters = ["x"]

[[keys]]
name = "SharingAs"
description = "Sharing as"

[[keys]]
name = "Connections"
description = "Connections"

[[keys]]
name = "Entities"
description = "Entities"

[[keys]]
name = "Connect"
description = "Connect"

[[keys]]
name = "ReceiverConfigurationMessage"
description = "Enter the credentials of the sender you want to connect to."

[[keys]]
name = "InviteCode"
description = "Invite code"

[[keys]]
name = "InvalidInviteCode"
description = "Invalid invite code"

[[keys]]
name = "CouldntConnectMessage"
description = "Couldn't establish connection. Invalid credentials?"

[[keys]]
name = "Connecting"
description = "Connecting..."
