name: Build (Linux x64)

on:
    workflow_dispatch:

env:
    OUTPUT_ARTIFACTS_DIR: "./output-artifacts"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              with:
                  node-version: 20

            - uses: subosito/flutter-action@v2
              with:
                  channel: beta

            - name: 🚧 Do prerequisites
              run: |
                  sudo apt-get update -y
                  sudo apt-get install -y ninja-build libgtk-3-dev
                  npm ci
                  flutter pub get

            - name: 📝 Fetch version
              id: version
              run: echo "version=$(npm run version:print --silent)" >> "$GITHUB_OUTPUT"

            - name: 🔨 Build artifacts
              run: npm run linux:build:x64

            - name: 🚀 Upload artifacts
              uses: ncipollo/release-action@v1
              with:
                  tag: v${{ steps.version.outputs.version }}
                  artifacts: ${{ env.OUTPUT_ARTIFACTS_DIR }}/*
                  generateReleaseNotes: true
                  draft: true
                  artifactErrorsFailBuild: true
